<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cercadornoms [
<!ELEMENT cercadornoms (nom+)><!ELEMENT nom (definicio,onomastica?,variant?,observacions?)>
<!ELEMENT definicio (#PCDATA)>
<!ELEMENT onomastica (#PCDATA)>
<!ELEMENT variant (#PCDATA)>
<!ELEMENT observacions (#PCDATA)>
<!ATTLIST cercadornoms data CDATA #REQUIRED>
<!ATTLIST nom numero CDATA #REQUIRED>
<!ATTLIST definicio catala CDATA #IMPLIED castella CDATA #IMPLIED>
<!ATTLIST variant catala CDATA #IMPLIED castella CDATA #IMPLIED>
]>
<cercadornoms data="12/19/13 10:02 AM">
<nom numero="1">
<definicio catala="Aaró" castella="Aarón"/>
<onomastica>01 de juliol</onomastica>
<variant/>
</nom>
<nom numero="2">
<definicio catala="Aaron" castella="Aarón"/>
<onomastica>01 de juliol</onomastica>
<variant/>
</nom>
<nom numero="3">
<definicio catala="Abdon" castella="Abdon"/>
<onomastica>30 de juliol</onomastica>
<variant/>
</nom>
<nom numero="4">
<definicio catala="Abel" castella="Abel"/>
<onomastica>25 de març</onomastica>
<variant/>
</nom>
<nom numero="5">
<definicio catala="Abelard" castella="Abelardo"/>
<onomastica>09 de febrer</onomastica>
<variant/>
</nom>
<nom numero="6">
<definicio catala="Abigaïl" castella="Abigail"/>
<onomastica></onomastica>
<variant/>
<observacions>Celebra el sant el 3 de febrer o el 19 de febrer. En català també és possible la forma Abigail.</observacions>
</nom>
<nom numero="7">
<definicio catala="Abra" castella="Abra"/>
<onomastica>12 de desembre</onomastica>
<variant catala="Variant femenina d'Abraham"/>
</nom>
<nom numero="8">
<definicio catala="Abraham" castella="Abraham"/>
<onomastica>16 de març</onomastica>
<variant/>
</nom>
<nom numero="9">
<definicio catala="Abril" castella="Abril"/>
<onomastica>30 de gener</onomastica>
<variant/>
<observacions>Originàriament era un nom masculí. Avui és també un nom femení.</observacions>
</nom>
<nom numero="10">
<definicio catala="Acab" castella="Acab"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom hebreu de l'Antic Testament.</observacions>
</nom>
<nom numero="11">
<definicio catala="Acaci" castella="Acacio"/>
<onomastica>01 d'abril</onomastica>
<variant/>
</nom>
<nom numero="12">
<definicio catala="Ada" castella="Ada"/>
<onomastica>04 de desembre</onomastica>
<variant/>
<observacions>Si és variant d'Immaculada, celebra el sant el 8 de desembre, si és variant d'Adela, el 8 de setembre.</observacions>
</nom>
<nom numero="13">
<definicio catala="Adalbert" castella="Adalberto"/>
<onomastica>24 de febrer</onomastica>
<variant catala="Variant d'Albert"/>
</nom>
<nom numero="14">
<definicio catala="Adam" castella="Adán"/>
<onomastica>29 de juliol</onomastica>
<variant/>
</nom>
<nom numero="15">
<definicio catala="Adela" castella="Adela"/>
<onomastica>08 de setembre</onomastica>
<variant/>
<observacions>També pot ser una variant d'Adelaida i aleshores celebra el sant el 3.10</observacions>
</nom>
<nom numero="16">
<definicio catala="Adelaida" castella="Adelaida"/>
<onomastica>03 d'octubre</onomastica>
<variant/>
</nom>
<nom numero="17">
<definicio catala="Adelard" castella="Adelardo"/>
<onomastica>02 de gener</onomastica>
<variant/>
</nom>
<nom numero="18">
<definicio catala="Adelf" castella="Adelfo"/>
<onomastica>29 d'agost</onomastica>
<variant/>
</nom>
<nom numero="19">
<definicio catala="Adelí" castella="Adelino"/>
<onomastica>03 de febrer</onomastica>
<variant/>
</nom>
<nom numero="20">
<definicio catala="Adelina" castella="Adelina"/>
<onomastica>03 de febrer</onomastica>
<variant/>
</nom>
<nom numero="21">
<definicio catala="Adelmar" castella="Adelmaro"/>
<onomastica>29 de maig</onomastica>
<variant/>
<observacions>Nom germànic.</observacions>
</nom>
<nom numero="22">
<definicio catala="Adolf" castella="Adolfo"/>
<onomastica>27 de setembre</onomastica>
<variant/>
</nom>
<nom numero="23">
<definicio catala="Adonis" castella="Adonis"/>
<onomastica>01 de novembre</onomastica>
<variant/>
</nom>
<nom numero="24">
<definicio catala="Adoració" castella="Adoración"/>
<onomastica>06 de gener</onomastica>
<variant/>
</nom>
<nom numero="25">
<definicio catala="Adrià" castella="Adrián"/>
<onomastica></onomastica>
<variant/>
<observacions>Celebra el sant el 6 de juliol o l'1 de març.</observacions>
</nom>
<nom numero="26">
<definicio catala="Adriana" castella="Adriana"/>
<onomastica></onomastica>
<variant/>
<observacions>Celebra el sant el 6 de juliol o l'1 de març.</observacions>
</nom>
<nom numero="27">
<definicio catala="Adrió" castella="Adrión"/>
<onomastica>17 de maig</onomastica>
<variant/>
<observacions>Pot ser variant d'Adrià i aleshores celebra el sant el 6 de juliol o l'1 de març.</observacions>
</nom>
<nom numero="28">
<definicio catala="Àfrica" castella="África"/>
<onomastica>05 d'agost</onomastica>
<variant/>
<observacions>Nom femení.</observacions>
</nom>
<nom numero="29">
<definicio catala="Agapit" castella="Agapito"/>
<onomastica>08 de juny</onomastica>
<variant/>
</nom>
<nom numero="30">
<definicio catala="Àgata" castella="Ágata"/>
<onomastica>05 de febrer</onomastica>
<variant/>
</nom>
<nom numero="31">
<definicio catala="Ageric" castella="Agerico"/>
<onomastica>01 de desembre</onomastica>
<variant/>
</nom>
<nom numero="32">
<definicio catala="Aglaè" castella="Aglaé"/>
<onomastica></onomastica>
<variant catala="Variant d'Aglaia"/>
</nom>
<nom numero="33">
<definicio catala="Aglaia" castella="Aglaia"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom femení de la mitologia grega.</observacions>
</nom>
<nom numero="34">
<definicio catala="Agnès" castella="Inés"/>
<onomastica>21 de gener</onomastica>
<variant/>
</nom>
<nom numero="35">
<definicio catala="Agrícola" castella="Agrícola"/>
<onomastica>17 de març</onomastica>
<variant/>
</nom>
<nom numero="36">
<definicio catala="Àgueda" castella="Águeda"/>
<onomastica>05 de febrer</onomastica>
<variant/>
</nom>
<nom numero="37">
<definicio catala="Agustí" castella="Agustín"/>
<onomastica>28 d'agost</onomastica>
<variant/>
</nom>
<nom numero="38">
<definicio catala="Agustina" castella="Agustina"/>
<onomastica>28 d'agost</onomastica>
<variant/>
</nom>
<nom numero="39">
<definicio catala="Ahmet" castella="Ahmed"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom àrab.</observacions>
</nom>
<nom numero="40">
<definicio catala="Àiax" castella="Ajax"/>
<onomastica></onomastica>
<variant/>
</nom>
<nom numero="41">
<definicio catala="Aida" castella="Aida"/>
<onomastica>02 de febrer</onomastica>
<variant/>
</nom>
<nom numero="42">
<definicio catala="Aïda" castella="Aída"/>
<onomastica>02 de febrer</onomastica>
<variant catala="Variant d'Aida" castella="Variant d'Aida"/>
</nom>
<nom numero="43">
<definicio catala="Aiman" castella="Aimano"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom germànic</observacions>
</nom>
<nom numero="44">
<definicio catala="Aimar" castella="Aimario"/>
<onomastica>29 de gener</onomastica>
<variant/>
<observacions>Nom germànic</observacions>
</nom>
<nom numero="45">
<definicio catala="Aina" castella="Ana"/>
<onomastica>26 de juliol</onomastica>
<variant catala="Variant d'Anna"/>
<observacions>Forma de les Illes Balears del nom Anna.</observacions>
</nom>
<nom numero="46">
<definicio catala="Ainara" castella="Ainara"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom basc</observacions>
</nom>
<nom numero="47">
<definicio catala="Ainhoa" castella="Ainhoa"/>
<onomastica>09 de setembre</onomastica>
<variant/>
</nom>
<nom numero="48">
<definicio catala="Ainoa" castella="Ainoa"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom basc</observacions>
</nom>
<nom numero="49">
<definicio catala="Ainona"/>
<onomastica>26 de juliol</onomastica>
<variant catala="Variant d'Anna"/>
</nom>
<nom numero="50">
<definicio catala="Aisha" castella="Aisha"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom àrab</observacions>
</nom>
<nom numero="51">
<definicio catala="Aitana" castella="Aitana"/>
<onomastica></onomastica>
<variant/>
</nom>
<nom numero="52">
<definicio catala="Aitor" castella="Aitor"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom basc</observacions>
</nom>
<nom numero="53">
<definicio catala="Aixa" castella="Aixa"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom àrab freqüent.</observacions>
</nom>
<nom numero="54">
<definicio catala="Akram" castella="Akram"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom àrab</observacions>
</nom>
<nom numero="55">
<definicio catala="Alan" castella="Alano"/>
<onomastica>14 d'agost</onomastica>
<variant/>
<observacions>Nom germànic</observacions>
</nom>
<nom numero="56">
<definicio catala="Alaric" castella="Alarico"/>
<onomastica>29 de setembre</onomastica>
<variant/>
<observacions>Nom germànic.</observacions>
</nom>
<nom numero="57">
<definicio catala="Alba" castella="Alba"/>
<onomastica>15 d'agost</onomastica>
<variant/>
</nom>
<nom numero="58">
<definicio catala="Albert" castella="Alberto"/>
<onomastica>15 de novembre</onomastica>
<variant/>
</nom>
<nom numero="59">
<definicio catala="Alberta" castella="Alberta"/>
<onomastica>15 de novembre</onomastica>
<variant/>
</nom>
<nom numero="60">
<definicio catala="Albertí" castella="Albertino"/>
<onomastica>31 d'agost</onomastica>
<variant/>
</nom>
<nom numero="61">
<definicio catala="Albertina" castella="Albertina"/>
<onomastica>31 d'agost</onomastica>
<variant/>
</nom>
<nom numero="62">
<definicio catala="Alegria" castella="Alegría"/>
<onomastica>08 de setembre</onomastica>
<variant/>
</nom>
<nom numero="63">
<definicio catala="Aleix" castella="Alejo"/>
<onomastica>17 de febrer</onomastica>
<variant/>
</nom>
<nom numero="64">
<definicio catala="Alena" castella="Alena"/>
<onomastica>03 de febrer</onomastica>
<variant catala="Variant d'Adelina" castella="Variant d'Adelina"/>
</nom>
<nom numero="65">
<definicio catala="Aleta" castella="Aleta"/>
<onomastica>08 de setembre</onomastica>
<variant catala="Variant d'Adela" castella="Variant d'Adela"/>
</nom>
<nom numero="66">
<definicio catala="Aleth" castella="Aleth"/>
<onomastica>04 d'abril</onomastica>
<variant catala="Variant d'Alícia" castella="Variant d'Alicia"/>
<observacions>Origen grec</observacions>
</nom>
<nom numero="67">
<definicio catala="Àlex" castella="Álex"/>
<onomastica>03 de maig</onomastica>
<variant catala="Variant d'Alexandre" castella="Variant d'Alejandro"/>
</nom>
<nom numero="68">
<definicio catala="Alexandra" castella="Alejandra"/>
<onomastica>03 de maig</onomastica>
<variant/>
</nom>
<nom numero="69">
<definicio catala="Alexandre" castella="Alejandro"/>
<onomastica>03 de maig</onomastica>
<variant/>
</nom>
<nom numero="70">
<definicio catala="Alèxia" castella="Alexia"/>
<onomastica></onomastica>
<variant/>
<observacions>Origen grec</observacions>
</nom>
<nom numero="71">
<definicio catala="Alexis" castella="Alexis"/>
<onomastica>12 de febrer</onomastica>
<variant catala="Variant d'Aleix" castella="Variant d'Alejo"/>
</nom>
<nom numero="72">
<definicio catala="Alfa" castella="Alfa"/>
<onomastica></onomastica>
<variant/>
</nom>
<nom numero="73">
<definicio catala="Alfons" castella="Alfonso"/>
<onomastica>01 d'agost</onomastica>
<variant/>
</nom>
<nom numero="74">
<definicio catala="Alfonsa" castella="Alfonsa"/>
<onomastica>01 d'agost</onomastica>
<variant/>
</nom>
<nom numero="75">
<definicio catala="Alfonsina" castella="Alfonsina"/>
<onomastica>01 d'agost</onomastica>
<variant catala="Variant d'Alfonsa" castella="Variant d'Alfonsa"/>
</nom>
<nom numero="76">
<definicio catala="Alfred" castella="Alfredo"/>
<onomastica>12 de gener</onomastica>
<variant/>
</nom>
<nom numero="77">
<definicio catala="Alí" castella="Alí"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom àrab</observacions>
</nom>
<nom numero="78">
<definicio catala="Alícia" castella="Alicia"/>
<onomastica>23 de juny</onomastica>
<variant/>
</nom>
<nom numero="79">
<definicio catala="Alina" castella="Alina"/>
<onomastica>03 de febrer</onomastica>
<variant catala="Variant d'Adelina" castella="Variant d'Adelina"/>
</nom>
<nom numero="80">
<definicio catala="Al·lodi" castella="Alodio"/>
<onomastica>22 d'octubre</onomastica>
<variant/>
</nom>
<nom numero="81">
<definicio catala="Al·lòdia" castella="Alodia"/>
<onomastica>22 d'octubre</onomastica>
<variant/>
</nom>
<nom numero="82">
<definicio catala="Alma" castella="Alma"/>
<onomastica></onomastica>
<variant/>
<observacions>Popularitzat a Anglaterra després de la batalla d'Alma, a la guerra de Crimea (1854)</observacions>
</nom>
<nom numero="83">
<definicio catala="Almeric" castella="Almárico"/>
<onomastica>29 de gener</onomastica>
<variant/>
</nom>
<nom numero="84">
<definicio catala="Alomar" castella="Alomar"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom germànic.</observacions>
</nom>
<nom numero="85">
<definicio catala="Alons" castella="Alonso"/>
<onomastica>01 d'agost</onomastica>
<variant catala="Variant d'Alfons" castella="Variant d'Alfons"/>
</nom>
<nom numero="86">
<definicio catala="Alsa" castella="Alsa"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom grec.</observacions>
</nom>
<nom numero="87">
<definicio catala="Altair" castella="Altair"/>
<onomastica></onomastica>
<variant/>
</nom>
<nom numero="88">
<definicio catala="Àlvar" castella="Álvaro"/>
<onomastica>19 de febrer</onomastica>
<variant/>
</nom>
<nom numero="89">
<definicio catala="Amada" castella="Amada"/>
<onomastica>31 d'agost</onomastica>
<variant/>
</nom>
<nom numero="90">
<definicio catala="Amades"/>
<onomastica>30 d'abril</onomastica>
<variant catala="Variant d'Amador"/>
</nom>
<nom numero="91">
<definicio catala="Amadeu" castella="Amadeo"/>
<onomastica>31 de març</onomastica>
<variant/>
</nom>
<nom numero="92">
<definicio catala="Amador" castella="Amador"/>
<onomastica>30 d'abril</onomastica>
<variant/>
</nom>
<nom numero="93">
<definicio catala="Amaia" castella="Amaya"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom basc</observacions>
</nom>
<nom numero="94">
<definicio catala="Amali" castella="Amalio"/>
<onomastica>10 de juliol</onomastica>
<variant/>
</nom>
<nom numero="95">
<definicio catala="Amàlia" castella="Amalia"/>
<onomastica>10 de juliol</onomastica>
<variant/>
</nom>
<nom numero="96">
<definicio catala="Amanda" castella="Amanda"/>
<onomastica>06 de febrer</onomastica>
<variant/>
</nom>
<nom numero="97">
<definicio catala="Amat" castella="Amado"/>
<onomastica>31 d'agost</onomastica>
<variant/>
</nom>
<nom numero="98">
<definicio catala="Ambròs" castella="Ambrosio"/>
<onomastica>07 de desembre</onomastica>
<variant/>
</nom>
<nom numero="99">
<definicio catala="Amèlia" castella="Amelia"/>
<onomastica>10 de juliol</onomastica>
<variant/>
</nom>
<nom numero="100">
<definicio catala="Amengual"/>
<onomastica>03 de novembre</onomastica>
<variant catala="Variant d'Ermengol"/>
</nom>
<nom numero="101">
<definicio catala="Amèric" castella="Américo"/>
<onomastica>29 de gener</onomastica>
<variant/>
</nom>
<nom numero="102">
<definicio catala="Amèrica" castella="América"/>
<onomastica></onomastica>
<variant/>
</nom>
<nom numero="103">
<definicio catala="Amílcar" castella="Amílcar"/>
<onomastica></onomastica>
<variant catala="Variant d'Hammílcar"/>
</nom>
<nom numero="104">
<definicio catala="Amín" castella="Amín"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom àrab</observacions>
</nom>
<nom numero="105">
<definicio catala="Amina" castella="Amina"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom àrab</observacions>
</nom>
<nom numero="106">
<definicio catala="Amir" castella="Amir"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom àrab</observacions>
</nom>
<nom numero="107">
<definicio catala="Amira" castella="Amira"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom àrab</observacions>
</nom>
<nom numero="108">
<definicio catala="Amor" castella="Amor"/>
<onomastica>08 d'octubre</onomastica>
<variant/>
</nom>
<nom numero="109">
<definicio catala="Anaclet" castella="Anacleto"/>
<onomastica>13 de juliol</onomastica>
<variant/>
</nom>
<nom numero="110">
<definicio catala="Anaïs" castella="Anaís"/>
<onomastica>26 de juliol</onomastica>
<variant catala="Variant d'Anna" castella="Variant d'Ana"/>
</nom>
<nom numero="111">
<definicio catala="Anastasi" castella="Anastasio"/>
<onomastica>05 de desembre</onomastica>
<variant/>
</nom>
<nom numero="112">
<definicio catala="Anastàsia" castella="Anastasia"/>
<onomastica>05 de desembre</onomastica>
<variant/>
</nom>
<nom numero="113">
<definicio catala="Andrea" castella="Andrea"/>
<onomastica>30 de novembre</onomastica>
<variant catala="Variant d'Andreua"/>
</nom>
<nom numero="114">
<definicio catala="Andreu" castella="Andrés"/>
<onomastica>30 de novembre</onomastica>
<variant/>
</nom>
<nom numero="115">
<definicio catala="Andreua" castella="Andrea"/>
<onomastica>30 de novembre</onomastica>
<variant/>
</nom>
<nom numero="116">
<definicio catala="Andròmac" castella="Andrómaco"/>
<onomastica>01 de novembre</onomastica>
<variant/>
<observacions>Nom mitològic.</observacions>
</nom>
<nom numero="117">
<definicio catala="Andròmaca" castella="Andrómaca"/>
<onomastica>01 de novembre</onomastica>
<variant/>
<observacions>Nom mitològic.</observacions>
</nom>
<nom numero="118">
<definicio catala="Anemone" castella="Anemone"/>
<onomastica></onomastica>
<variant/>
</nom>
<nom numero="119">
<definicio catala="Àngel" castella="Ángel"/>
<onomastica>05 de març</onomastica>
<variant/>
</nom>
<nom numero="120">
<definicio catala="Àngela" castella="Ángela"/>
<onomastica>05 de març</onomastica>
<variant/>
</nom>
<nom numero="121">
<definicio catala="Angeleta" castella="Angelita"/>
<onomastica>15 de juliol</onomastica>
<variant catala="Variant d'Àngela" castella="Variant d'Ángela"/>
</nom>
<nom numero="122">
<definicio catala="Angèlica" castella="Angélica"/>
<onomastica></onomastica>
<variant/>
</nom>
<nom numero="123">
<definicio catala="Angelina" castella="Angelina"/>
<onomastica>15 de juliol</onomastica>
<variant catala="Variant d'Àngela" castella="Variant d'Ángela"/>
</nom>
<nom numero="124">
<definicio catala="Àngels" castella="Ángeles"/>
<onomastica>02 d'agost</onomastica>
<variant/>
</nom>
<nom numero="125">
<definicio catala="Anicet" castella="Aniceto"/>
<onomastica>12 d'agost</onomastica>
<variant/>
</nom>
<nom numero="126">
<definicio catala="Aniol" castella="Aniano"/>
<onomastica></onomastica>
<variant/>
<observacions>Celebra el sant l'1 de maig o el 17 d'octubre.</observacions>
</nom>
<nom numero="127">
<definicio catala="Anna" castella="Ana"/>
<onomastica>26 de juliol</onomastica>
<variant/>
</nom>
<nom numero="128">
<definicio catala="Annabel" castella="Anabel"/>
<onomastica></onomastica>
<variant catala="Variant aglutinada d'Anna Isabel" castella="Variant aglutinada d'Ana Isabel"/>
</nom>
<nom numero="129">
<definicio catala="Annanies" castella="Ananías"/>
<onomastica>25 de gener</onomastica>
<variant/>
<observacions>Nom hebreu de l'Antic Testament</observacions>
</nom>
<nom numero="130">
<definicio catala="Annàs" castella="Anás"/>
<onomastica>25 de gener</onomastica>
<variant catala="Forma contracta d'Annanies" castella="Forma contracta d'Ananías"/>
</nom>
<nom numero="131">
<definicio catala="Ànnia" castella="Ania"/>
<onomastica>31 d'agost</onomastica>
<variant/>
</nom>
<nom numero="132">
<definicio catala="Anselm" castella="Anselmo"/>
<onomastica>21 d'abril</onomastica>
<variant/>
</nom>
<nom numero="133">
<definicio catala="Anselma" castella="Anselma"/>
<onomastica>21 d'abril</onomastica>
<variant/>
</nom>
<nom numero="134">
<definicio catala="Anstruda" castella="Anstruda"/>
<onomastica>17 d'octubre</onomastica>
<variant/>
</nom>
<nom numero="135">
<definicio catala="Anton" castella="Antón"/>
<onomastica>13 de juny</onomastica>
<variant catala="Variant d'Antoni" castella="Variant d'Antonio"/>
</nom>
<nom numero="136">
<definicio catala="Antoni" castella="Antonio"/>
<onomastica>13 de juny</onomastica>
<variant/>
</nom>
<nom numero="137">
<definicio catala="Antoní" castella="Antonino"/>
<onomastica>30 de setembre</onomastica>
<variant/>
</nom>
<nom numero="138">
<definicio catala="Antònia" castella="Antonia"/>
<onomastica>13 de juny</onomastica>
<variant/>
</nom>
<nom numero="139">
<definicio catala="Anunciació" castella="Anunciación"/>
<onomastica>25 de març</onomastica>
<variant/>
</nom>
<nom numero="140">
<definicio catala="Aparici" castella="Aparicio"/>
<onomastica>06 de gener</onomastica>
<variant/>
</nom>
<nom numero="141">
<definicio catala="Apel·les" castella="Apeles"/>
<onomastica>22 d'abril</onomastica>
<variant/>
</nom>
<nom numero="142">
<definicio catala="Apol·linar" castella="Apolinar"/>
<onomastica>05 de gener</onomastica>
<variant/>
</nom>
<nom numero="143">
<definicio catala="Apol·loni" castella="Apolonio"/>
<onomastica>14 de febrer</onomastica>
<variant/>
</nom>
<nom numero="144">
<definicio catala="Apol·lònia" castella="Apolonia"/>
<onomastica>14 de febrer</onomastica>
<variant/>
</nom>
<nom numero="145">
<definicio catala="Aquilí" castella="Aquilino"/>
<onomastica>16 de maig</onomastica>
<variant/>
</nom>
<nom numero="146">
<definicio catala="Aquil·les" castella="Aquiles"/>
<onomastica>07 de gener</onomastica>
<variant/>
</nom>
<nom numero="147">
<definicio catala="Aquil·lí" castella="Aquilino"/>
<onomastica>16 de maig</onomastica>
<variant/>
</nom>
<nom numero="148">
<definicio catala="Aquil·lina" castella="Aquilina"/>
<onomastica>16 de maig</onomastica>
<variant/>
</nom>
<nom numero="149">
<definicio catala="Araceli" castella="Araceli"/>
<onomastica>02 de maig</onomastica>
<variant/>
</nom>
<nom numero="150">
<definicio catala="Aram" castella="Aram"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom bíblic.</observacions>
</nom>
<nom numero="151">
<definicio catala="Aran" castella="Arán"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom bíblic (masc.) 
Relacionat amb la Vall (fem.)</observacions>
</nom>
<nom numero="152">
<definicio catala="Arantxa" castella="Arancha"/>
<onomastica>09 de setembre</onomastica>
<variant catala="Variant d'Arantzazu" castella="Variant d'Aránzazu"/>
</nom>
<nom numero="153">
<definicio catala="Arantzazu" castella="Aránzazu"/>
<onomastica>09 de setembre</onomastica>
<variant/>
</nom>
<nom numero="154">
<definicio catala="Arcadi" castella="Arcadio"/>
<onomastica>12 de gener</onomastica>
<variant/>
</nom>
<nom numero="155">
<definicio catala="Arcàdia" castella="Arcadia"/>
<onomastica>12 de gener</onomastica>
<variant/>
</nom>
<nom numero="156">
<definicio catala="Ares" castella="Ares"/>
<onomastica>08 de setembre</onomastica>
<variant/>
</nom>
<nom numero="157">
<definicio catala="Argemí" castella="Argimiro"/>
<onomastica>21 de juliol</onomastica>
<variant/>
</nom>
<nom numero="158">
<definicio catala="Arià" castella="Ariano"/>
<onomastica>07 de març</onomastica>
<variant/>
</nom>
<nom numero="159">
<definicio catala="Ariadna" castella="Ariadna"/>
<onomastica>17 de setembre</onomastica>
<variant/>
</nom>
<nom numero="160">
<definicio catala="Ariana" castella="Ariana"/>
<onomastica>07 de març</onomastica>
<variant/>
</nom>
<nom numero="161">
<definicio catala="Aridna" castella="Aridna"/>
<onomastica>17 de setembre</onomastica>
<variant catala="Variant d'Ariadna" castella="Variant d'Ariadna"/>
</nom>
<nom numero="162">
<definicio catala="Ariel" castella="Ariel"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom bíblic.</observacions>
</nom>
<nom numero="163">
<definicio catala="Arlet" castella="Arlet"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom medieval francès</observacions>
</nom>
<nom numero="164">
<definicio catala="Armand" castella="Armando"/>
<onomastica>23 de gener</onomastica>
<variant/>
</nom>
<nom numero="165">
<definicio catala="Armanda" castella="Armanda"/>
<onomastica>23 de gener</onomastica>
<variant/>
</nom>
<nom numero="166">
<definicio catala="Armengol" castella="Armengol"/>
<onomastica>03 de novembre</onomastica>
<variant catala="Variant d'Ermengol" castella="Variant d'Ermengol"/>
</nom>
<nom numero="167">
<definicio catala="Arnau" castella="Arnaldo"/>
<onomastica>16 de febrer</onomastica>
<variant/>
</nom>
<nom numero="168">
<definicio catala="Aroa" castella="Aroa"/>
<onomastica>05 de juliol</onomastica>
<variant/>
</nom>
<nom numero="169">
<definicio catala="Arseni" castella="Arsenio"/>
<onomastica>19 de gener</onomastica>
<variant/>
</nom>
<nom numero="170">
<definicio catala="Artemi" castella="Artemio"/>
<onomastica></onomastica>
<variant/>
<observacions>Celebra el sant el 6 de juny o el 20 d'octubre.</observacions>
</nom>
<nom numero="171">
<definicio catala="Àrtemis" castella="Artemisa"/>
<onomastica>25 de gener</onomastica>
<variant/>
<observacions>Nom mitològic.</observacions>
</nom>
<nom numero="172">
<definicio catala="Artur" castella="Arturo"/>
<onomastica>01 de setembre</onomastica>
<variant/>
</nom>
<nom numero="173">
<definicio catala="Ascensió" castella="Ascensión"/>
<onomastica></onomastica>
<variant/>
<observacions>Celebra el sant 40 dies després de Pasqua.</observacions>
</nom>
<nom numero="174">
<definicio catala="Asdrúbal" castella="Asdrúbal"/>
<onomastica></onomastica>
<variant/>
</nom>
<nom numero="175">
<definicio catala="Àsia" castella="Asia"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom femení.</observacions>
</nom>
<nom numero="176">
<definicio catala="Asier" castella="Asier"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom basc</observacions>
</nom>
<nom numero="177">
<definicio catala="Assumpció" castella="Asunción"/>
<onomastica>15 d'agost</onomastica>
<variant/>
</nom>
<nom numero="178">
<definicio catala="Assumpta" castella="Asunta"/>
<onomastica>15 d'agost</onomastica>
<variant catala="Variant d'Assumpció" castella="Variant d'Asunción"/>
</nom>
<nom numero="179">
<definicio catala="Assutzena" castella="Azucena"/>
<onomastica>15 d'agost</onomastica>
<variant/>
</nom>
<nom numero="180">
<definicio catala="Astrid" castella="Astrid"/>
<onomastica>17 d'octubre</onomastica>
<variant/>
<observacions>Nom germànic variant d'Anstruda.</observacions>
</nom>
<nom numero="181">
<definicio catala="Asun" castella="Asun"/>
<onomastica>15 d'agost</onomastica>
<variant/>
<observacions>Variant castellana d'Assumpció.</observacions>
</nom>
<nom numero="182">
<definicio catala="Atalanta" castella="Atalanta"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom mitològic.</observacions>
</nom>
<nom numero="183">
<definicio catala="Atanasi" castella="Atanasio"/>
<onomastica>12 d'agost</onomastica>
<variant/>
</nom>
<nom numero="184">
<definicio catala="Atanàsia" castella="Atanasia"/>
<onomastica>12 d'agost</onomastica>
<variant/>
</nom>
<nom numero="185">
<definicio catala="Atenea" castella="Atenea"/>
<onomastica>28 de setembre</onomastica>
<variant/>
<observacions>Nom mitològic.</observacions>
</nom>
<nom numero="186">
<definicio catala="Audrey"/>
<onomastica>18 de juny</onomastica>
<variant catala="Variant anglesa d'Edeltrudis"/>
</nom>
<nom numero="187">
<definicio catala="August" castella="Augusto"/>
<onomastica>07 d'octubre</onomastica>
<variant/>
</nom>
<nom numero="188">
<definicio catala="Augusta" castella="Augusta"/>
<onomastica>07 d'octubre</onomastica>
<variant/>
</nom>
<nom numero="189">
<definicio catala="Aulí" castella="Aulina"/>
<onomastica>12 de febrer</onomastica>
<variant/>
</nom>
<nom numero="190">
<definicio catala="Aulina" castella="Aulina"/>
<onomastica>12 de febrer</onomastica>
<variant/>
</nom>
<nom numero="191">
<definicio catala="Aura" castella="Aura"/>
<onomastica>04 d'octubre</onomastica>
<variant catala="Variant d'Òria" castella="Variant d'Oria"/>
</nom>
<nom numero="192">
<definicio catala="Aure" castella="Áureo"/>
<onomastica>16 de juny</onomastica>
<variant/>
</nom>
<nom numero="193">
<definicio catala="Àurea" castella="Áurea"/>
<onomastica>04 d'octubre</onomastica>
<variant/>
</nom>
<nom numero="194">
<definicio catala="Aureli" castella="Aurelio"/>
<onomastica>27 de juliol</onomastica>
<variant/>
</nom>
<nom numero="195">
<definicio catala="Aurèlia" castella="Aurelia"/>
<onomastica>27 de juliol</onomastica>
<variant/>
</nom>
<nom numero="196">
<definicio catala="Àuria" castella="Auria"/>
<onomastica>04 d'octubre</onomastica>
<variant catala="Variant d'Àurea" castella="Variant d'Áurea"/>
</nom>
<nom numero="197">
<definicio catala="Aurora" castella="Aurora"/>
<onomastica>08 de setembre</onomastica>
<variant/>
</nom>
<nom numero="198">
<definicio catala="Ausiàs" castella="Ausias"/>
<onomastica>04 de juliol</onomastica>
<variant/>
</nom>
<nom numero="199">
<definicio catala="Auxili" castella="Auxilio"/>
<onomastica>27 de novembre</onomastica>
<variant/>
<observacions>També pot ser una variant d'Auxiliadora.</observacions>
</nom>
<nom numero="200">
<definicio catala="Auxiliadora" castella="Auxiliadora"/>
<onomastica>24 de maig</onomastica>
<variant/>
</nom>
<nom numero="201">
<definicio catala="Avelí" castella="Avelino"/>
<onomastica>31 de maig</onomastica>
<variant catala="Variant d'Avel·lí"/>
</nom>
<nom numero="202">
<definicio catala="Avel·lí" castella="Avelino"/>
<onomastica>31 de maig</onomastica>
<variant/>
</nom>
<nom numero="203">
<definicio catala="Axel" castella="Axel"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom masculí, freqüent als països nòrdics.</observacions>
</nom>
<nom numero="204">
<definicio catala="Aya" castella="Aya"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom àrab</observacions>
</nom>
<nom numero="205">
<definicio catala="Ayman" castella="Ayman"/>
<onomastica></onomastica>
<variant/>
<observacions>Nom àrab</observacions>
</nom>
<nom numero="206">
<definicio catala="Azalea" castella="Azalea"/>
<onomastica></onomastica>
<variant/>
</nom>
<nom numero="207">
<definicio catala="Azrael" castella="Azrael"/>
<onomastica>01 de novembre</onomastica>
<variant/>
</nom>
<nom numero="208">
<definicio catala="Babet" castella="Babet"/>
<onomastica>05 de novembre</onomastica>
<variant catala="Variant d'Elisabet"/>
</nom>
<nom numero="209">
<definicio catala="Balbí" castella="Balbino"/>
<onomastica>31 de març</onomastica>
<variant/>
</nom>
<nom numero="210">
<definicio catala="Balbina" castella="Balbina"/>
<onomastica>31 de març</onomastica>
<variant/>